### ISSUE TITLE
Prediction set size calculation

### ISSUE THREAD

**Issue by eliahuhorwitz** [aangelopoulos/im2im-uq#2]
Hey,
Thank you for publishing the paper and for providing such an extensive code base. 
I have a question regarding the calculation of the prediction set size. In the function ``get_rcps_metrics_from_outputs`` it seems the calculation of the size of the set is done based on random pixels (as seen below), is this indeed the case? 
If this is indeed the case, could you please explain why would we prefer this to taking the average size across pixels?
```
sets_full = (sets[2]-sets[0]).flatten(start_dim=1).detach().cpu().numpy()
size_random_idxs = np.random.choice(sets_full.shape[1],size=sets_full.shape[0])  
size_samples = sets_full[range(sets_full.shape[0]),size_random_idxs]  
sizes = sizes + [torch.tensor(size_samples),]  
```

Thanks,
Eliahu

**Comment by aangelopoulos** [comment]
The average size across pixels is just a different quantity with lower variance. In this paper, we preferred to make a histogram of the per-pixel set sizes to show that they vary (there are some pixels with very small sets, and some with large sets). We didn't want to store every single pixel's interval size, so we just took a small random sample.  You only need a few hundred randomly sampled pixelwise interval sizes in order to make an adequate histogram.
